#!/usr/bin/env bash
# displays listining active ports
# + as the PID and name of the program to which each socket belongs.

# Get the list of listening ports
listening_ports=$(netstat -lnp | grep LISTEN | awk '{print $4}')

# Display the list of listening ports
for port in $listening_ports; do
  echo "Listening on port: $port"
done
